### ISSUE TITLE
`format` options to specify custom file formatter

### ISSUE THREAD

**Issue by davidosomething** [unifiedjs/unified-engine#16]
Create a vim errorformat processor like atom's unified processor to https://github.com/wooorm/unified-engine-atom

-- basically having everything on one line with single character (space or colon, doesn't matter) delimiters. This translates to `%f:%l:%c %tarning %m` in vim's errorformat (where `%t` captures the first character to get the warning/error type, using the literal arning is optional, a `%*` group could be used instead)

source: https://github.com/davidosomething/projects/issues/1#issuecomment-251309471

**Comment by wooorm** [comment]
Oh, lol, that’s also possible, but IMO a better, more future proof solution would be to add a `--format` flag (in unified-args) and `format` option here, which get’s a name, such as `reporter`, which resolves to `vfile-reporter`, loads it, and calls that function with the files.

Then, you can create a module / file which prints exactly the way anyone may ever need.

**Comment by wooorm** [comment]
👍 I’ve updated the title.

Any suggestions?

**Comment by wooorm** [comment]
@davidosomething Would you be interested in creating a reporter? Something that receives `Array.<VFile>` and returns `string`?

I’m thinking of doing something with [`code-frame`](https://github.com/hhsnopek/code-frame) now, but not sure what time it’ll take.

**Comment by davidosomething** [comment]
Sure I can take this on

**Comment by wooorm** [comment]
Closed by e720037!

**Comment by davidosomething** [comment]
oops way to do nothing on my part XP
GREAT JOB @wooorm

**Comment by wooorm** [comment]
Oh no problem! And thanks! 🍻
