### ISSUE TITLE
Warning on install

### ISSUE THREAD

**Issue by evilebottnawi** [unifiedjs/unified-engine#24]
```shell
warning remark-cli > unified-args > unified-engine > isarray@2.0.1: Just use Array.isArray directly
```
Latest stable node version support `Array.isArray`. Can we use this instead `isarray`?

**Comment by wooorm** [comment]
Dupe of https://github.com/unifiedjs/unified/issues/30!
I just might remove it though, if more people complain :)

**Comment by evilebottnawi** [comment]
@wooorm thanks for answer :smile:
