### ISSUE TITLE
Document configTransform takes second argument of filePath

### ISSUE THREAD

**Issue by appden** [unifiedjs/unified-engine#25]
It's really useful that the second argument is the path to the config file, but it makes me nervous that this could go away if it's not actually documented. Thanks! :smile:

**Comment by wooorm** [comment]
:+1:

Would you be interested in doing a PR for the docs?

**Comment by appden** [comment]
@wooorm Sorry your reply fell off my radar. Thanks for doing that!

**Comment by wooorm** [comment]
No problem! :)
