### ISSUE TITLE
Don’t throw exception if globs or file-paths to directories are given, but none are found

### ISSUE THREAD

**Issue by wooorm** [unifiedjs/unified-engine#29]
Currently there’s a “No input” error:

```sh
λ remark . -qfo
Error: No input
    at stdin (/Users/niftylettuce/Public/lad/template/node_modules/unified-engine/lib/file-set-pipeline/stdin.js:30:10)
    ...
```

...but as there’s actually “input”, the error is weird.

I think the exception should still be thrown if nothing is passed in.

Supersedes wooorm/remark#294.

**Comment by OmgImAlexis** [comment]
The error should really only be thrown if this was to be used programmatically where the user can then decide what to do, when used in a cli it should really just return nothing like most other clis do.

**Comment by wooorm** [comment]
@OmgImAlexis Hello! 👋 Welcome to the community & nice to meet you! 

I think you’re misunderstanding what I’m proposing and reiterating what I meant.

For example ESLint also throws without input:

```sh
$ eslint
eslint [options] file.js [file.js] [dir]

Basic configuration:
  -c, --config path::String    Use configuration from this file or shareable config
...
```

...and stylelint:

```sh
$ stylelint 

  A mighty, modern CSS linter.

  Usage: stylelint [input] [options]

  Input: Files(s), glob(s), or nothing to use stdin.
```

...and I propose remark keeps doing so too.

**Comment by niftylettuce** [comment]
Could we please make the remark CLI behave just as other CLI's do when no input is given?  `xo`, `prettier`, `eslint`, etc all do not throw an error when no input is given.  Thank you!!

**Comment by OmgImAlexis** [comment]
Neither of those examples throw an error though and you're also comparing passing `.` vs no argument. They're not the same thing as shown by the error.

**Comment by wooorm** [comment]
@niftylettuce
> Could we please make the remark CLI behave just as other CLI's do when no input is given? xo, prettier, eslint, etc all do not throw an error when no input is given. Thank you!!

That’s why this issue is here and the "needs pr" label is attached 🤷‍♂️

@OmgImAlexis “They're not the same thing as shown by the error” is what this issue is solving, and what I’ve tried to explain three times now...
