### ISSUE TITLE
Access to original sourcecode inside plugins

### ISSUE THREAD

**Issue by StarpTech** [unifiedjs/unified-engine#31]
Hi,
is it possible to access the original sourcecode inside a plugin? I have to inspect the original sourcecode via the tag, attribute positions. Thanks.

**Comment by wooorm** [comment]
Is this Q about this project? Or more for unist (the syntax tree format) itself?

To answer it, I believe [`unist-util-source`](https://github.com/syntax-tree/unist-util-source) is what you’re looking for!

**Comment by StarpTech** [comment]
No, I mean how can I access the raw file inside unified when I parse a bunch of files? At the point of processing I don't where in which file the data is stored.

**Comment by wooorm** [comment]
What is “the raw file”? [transformer](https://github.com/unifiedjs/unified#function-transformernode-file-next)s are given the syntax tree and the corresponding file.

**Comment by StarpTech** [comment]
Oh, I didn't know it. I missed the information. Thanks!

**Comment by wooorm** [comment]
Yeah, the unified readme is a great intro to the whole system! and the [website](https://unifiedjs.github.io) too!
