### ISSUE TITLE
settings.output will create an empty file when file does not exist

### ISSUE THREAD

**Issue by StarpTech** [unifiedjs/unified-engine#34]
Executing this command with the option `output: true` will create an empty file `test.html`

```
cli.js test.html
```

An error is displayed but the file is still created.

```
test.html
  1:1  error  No such file or directory

× 1 error
```
I expect that no file is created and an error is emitted.

**Comment by wooorm** [comment]
Oh that sound weird, and what you're suggesting sounds way more logical! PRS welcome!

**Comment by StarpTech** [comment]
Yes, but no glob only a single file.
