### ISSUE TITLE
Ability to suppress error "Cannot process specified file: it’s ignored"

### ISSUE THREAD

**Issue by foray1010** [unifiedjs/unified-engine#47]
### Subject of the feature

Do not throw error when running with ignored file

### Problem

I am using remark-cli with [lint-staged](https://github.com/okonet/lint-staged), lint-staged doesn't know the content in .remarkignore, so it will try to run on all modified md files with remark-cli. But as the file is ignored by remark-cli, it throws error `Cannot process specified file: it’s ignored`

### Expected behavior

I can use remark-cli with lint-staged without any errors

### Alternatives

As it may be a breaking change, maybe a flag to enable?

**Comment by wooorm** [comment]
The engine has a [`silentlyIgnore`](https://github.com/unifiedjs/unified-engine/blob/master/doc/options.md#optionssilentlyignore) option that allows this; unified-args doesn’t, and I kinda think that’s correct behavior.

---

The current behavior also resembles ESLint, say we had `example.js`:

```js
console.log(1)
```

and `.eslintrc.json`:

```json
{
  "extends": "eslint:recommended"
}
```

...now, if we’d run `eslint example.js`, we’d get:

```
  1:1  error  'console' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)
```

...and if we’d add an `.eslintignore`:

```
example.js
```

...we’d get:

```
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override

✖ 1 problem (0 errors, 1 warning)
```

---

Here’s what ESLint decided on the [topic](https://github.com/okonet/lint-staged/issues/696), and I feel similar, and you can solve this on lint-staged’s side as described in [their docs](https://github.com/okonet/lint-staged#example-ignore-files-from-match).

**Comment by foray1010** [comment]
thank you! I figure that it will be too much work to filter the files in lint-staged, as normally there are just a few markdown files per repo. I finally go for running on all markdown files in lint-staged.

**Comment by muravjev** [comment]
> thank you! I figure that it will be too much work to filter the files in lint-staged ...

Unfortunately, if there are many md files in repo it is a problem. And it should be solved twice: in `.remarkignore` and in `.lintstagedrc.js`, and then kept the solution in sync.

Great suggestion, @foray1010 .

P.S. I guess many people (as me) don't even suspect, that .remarkignore not working in lint-staged :(

P.P.S: [Ignore files in lint-staged level](https://github.com/okonet/lint-staged#example-ignore-files-from-match)

**Comment by foray1010** [comment]
@muravjev Now remark-cli supports `--silently-ignore` flag, I have been able to [run on modified markdown files only](https://github.com/foray1010/common-presets/blob/master/.lintstagedrc.mjs#L7) for a while.
