### ISSUE TITLE
Ignored files are accounted for in processing list and result in non-zero exit code

### ISSUE THREAD

**Issue by JeffersonBledsoe** [unifiedjs/unified-engine#48]
### Subject of the issue
Files that are in the ignore list are still added to the list of files to process. This makes it difficult to easily run the engine against a large directory (e.g. one that contains node_modules) using a `**/**` glob as it will find the argument list is too long. Additionally, it makes it more difficult to use within CI, as trying to process and ignored file results in an error being produced rather than silently skipping over files the user has already marked as not wanting to be accounted for.

### Steps to reproduce
1. Add a file name to the `ignoreName` list when calling engine

### Expected behaviour
The engine silently ignored the file, acting as if the file doesn't exist and not attempting to process it. The engine would producing a 'no files were found' message if the user tried to process only ignored file.

### Actual behaviour
The error message `error  Cannot process specified file: it’s ignored` is produced and a non-zero return code returned.

**Comment by wooorm** [comment]
There’s a silentlyIgnore options, that does your expected behavior: https://github.com/unifiedjs/unified-engine/blob/main/doc/options.md#optionssilentlyignore. Correct?

Ignoring files happens after finding them, because from the file, it starts looking for an ignore file, to see if that includes it. Can’t be reversed.

**Comment by JeffersonBledsoe** [comment]
Don't know how I missed that config option. Thanks for the help @wooorm!
