### ISSUE TITLE
accept `VFile` without `path` as `options.files` input

### ISSUE THREAD

**Issue by stefanprobst** [unifiedjs/unified-engine#51]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

i am trying to use `unified-engine` in a vscode extension to lint markdown/mdx, similar to [this](https://github.com/drewbourne/vscode-remark-lint/blob/master/src/extension.ts) one.

this works great when feeding `unified-engine` a `VFile` with an actual on-disk file path. however, it seems that it is not possible to feed it a `VFile` without a valid file path - for example to lint unsaved files, for which vscode does not provide a file path.

### Solution

the following should work:

```js
import { VFile } from "vfile";
import remark from "remark";
import engine from "unified-engine";

const file = new VFile({ value: "Some text" });

engine(
  {
    processor: remark,
    files: [file],
  },
  function done(error, code) {
    if (error) throw error;
  }
);
```

but throws:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.relative (path.js:1168:5)
    at each (/data/Development/playground/engine/node_modules/unified-engine/lib/finder.js:53:24)
```

### Alternatives

not sure

**Comment by wooorm** [comment]
This might be a problem because `VFile` is already updated to support `file.value` instead of `file.contents`, whereas unified et al are not yet released to support that.
I’m guessing that that’s why the error is thrown (it’s seen as an empty file that thus has to be read).
Perhaps you could use the older VFile for now to work with unified-engine?

I‘ve already updated the code for `unified-engine`, but have not yet released it

**Comment by stefanprobst** [comment]
hmm, i tried with `vfile@4` but get the same error message:

```js
import vfile from "vfile";
import remark from "remark";
import engine from "unified-engine";

const file = vfile({ contents: "Some text" });

engine(
  {
    processor: remark,
    files: [file],
  },
  function done(error, code) {
    if (error) throw error;
  }
);
```

error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.relative (path.js:1168:5)
    at each (/data/Development/playground/engine/node_modules/unified-engine/lib/finder.js:53:24)
```

i am using these versions:

```json
  "dependencies": {
    "remark": "^13.0.0",
    "unified-engine": "^8.2.0",
    "vfile": "^4.2.1"
  }
```

**Comment by stefanprobst** [comment]
this is the line where a vfile.path is required (and which fails with the above):

v8.2.0:
https://github.com/unifiedjs/unified-engine/blob/992cb7c04a3d65806566df5b1404d3749f583931/lib/finder.js#L53

**Comment by wooorm** [comment]
Thanks for the repro. I opened a PR that fixes it.

I would strongly suggest to add a `path` to your files when possible, even if VSCode doesn’t. The engine does a lot of file system related reading/looking up/writing, which needs paths

**Comment by stefanprobst** [comment]
thank you! :tada:
