### ISSUE TITLE
Don’t ignore dotfiles by default

### ISSUE THREAD

**Issue by remcohaszing** [unifiedjs/unified-engine#55]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

IMO it’s a bad practice to exclude dotfiles from a project’s code quality standards such as `remark-lint`. I.e. I don’t understand why one wouldn’t want to check the various markdown files in the `.github` or `.gitlab` directory.

Currently there appears to be no way to include dotfiles, except by explicitly passing the dotfile to the CLI.

I think this idea originates from ESLint (where I also think it’s a bad idea), but at least ESLint allows to unignore dotfiles by adding the following `.eslintignore` file:

```ignore
!.*
```

This doesn’t work for `.remarkignore`.

### Solution

Don’t ignore dotfiles by default.

### Alternatives

Allow to unignore dotfiles.

**Comment by wooorm** [comment]
- yeah, idea behind it is that eslint did the same
- I believe some dependency, `node-ignore` perhaps, switched at some point to no longer support negated patterns.
- different tools add dot files for various reasons, `.github` is a good case where checking them might make sense, but I feel like there are more cases where dotfiles contains garbage that shouldn’t be checked? (similar: `node_modules/` often contains packages pulled in from npm, but you can also use it manually to manage your monorepo)

I’d rather *add* support for negated patterns rather than *change* the default?

**Comment by remcohaszing** [comment]
Personally I have yet to find a situation where I want to skip checking for a dotfile. All of my projects explicitly unignore them for ESLint. Also Prettier for example doesn’t ignore dotfiles by default.

**Comment by wooorm** [comment]
prettier takes `.gitignore` by default though, right?
And folks have these giant gitignore often: https://github.com/github/gitignore/blob/master/Node.gitignore.

**Comment by remcohaszing** [comment]
> prettier takes `.gitignore` by default though, right?

Nope https://github.com/prettier/prettier/issues/8506

> And folks have these giant gitignore often: https://github.com/github/gitignore/blob/master/Node.gitignore.

Personally not a fan :sweat_smile: 

Anyway, this doesn’t ignore dotfiles either.

**Comment by wooorm** [comment]
ah it’s xo, which I was thinking of.

> Personally not a fan 😅

Same.

> Anyway, this doesn’t ignore dotfiles either.

It ignores many dotfiles. Which is what I’m trying to point out (earlier point):

> different tools add dot files for various reasons, `.github` is a good case where checking them might make sense, but I feel like there are more cases where dotfiles contains garbage that shouldn’t be checked? (similar: `node_modules/` often contains packages pulled in from npm, but you can also use it manually to manage your monorepo).

There are some cases where dotfiles should be checked. There are many cases where dotfiles shouldn’t be checked.
You’re proposing to change the default. I think the default should make sense in most cases. I think the default of dotfiles and `node_modules/` is most sensical.

Are there common cases, other than `.github` and `.gitlab`, which you believe should be checked?

**Comment by wooorm** [comment]
How acceptable do you see the alternative?

**Comment by remcohaszing** [comment]
I can think of many more cases of dotfiles that I would like to be checked if a linter is available, namely every dotfile I’ve ever checked into source control and has a linter available. I can’t think of any markdown file other than those inside `.github/` or `.gitlab/`, but if they appear, I’d like them to be checked unless they’re explicitly ignored.

Since this isn’t related specifically to markdown, I can think of a practical list of files that should be linted IMO:

- `.babelrc.js`
- `.eslintrc.js`
- `.lighthouserc.js` (it isn’t different from `lighthouse.config.js` apart from the name)
- `.prettierc.js` (it isn’t different from `prettier.config.js` apart from the name)
- `.stylelintrc.js` (it isn’t different from `stylelint.config.js` apart from the name)
- etc.

My point is the dot prefix doesn’t make them special. It just means they don’t show up in typical file explorers and `ls` without flags.

There are some special cases of files which I think should be ignored by default, but this determined by their purpose, not their filename:

- `.git/`
- `.hg/`
- `.svn/`
- `bower_components/` (Is this still relevant)
- `node_modules/`

Typically my `.{name}ignore` matches `.gitignore`, except maybe some additional special cases are added.

---

> How acceptable do you see the alternative?

I wouldn’t like it, because IMO this means every repository that has issue templates needs an ignore file to unignore dotfiles. However, changing default behaviour would be a breaking change (semver major), whereas adding the ability to unignore files is a feature (semver minor).

**Comment by wooorm** [comment]
> I can think of many more cases of dotfiles that I would like to be checked if a linter is available, namely every dotfile I’ve ever checked into source control and has a linter available
> Typically my `.{name}ignore` matches `.gitignore`, except maybe some additional special cases are added.

Copy/pasting and manually syncing your `.gitignore` file into every linter’s ignore file (prettierignore, eslintignore, remarkignore) seems like a lot of work to me. Are you saying you’re doing this? I believe most linters allow you to pass the `.gitignore` file to them. You can do the same with `unified-engine`?

> My point is the dot prefix doesn’t make them special. It just means they don’t show up in typical file explorers and ls without flags.

I think it was a mistake to prefix configuration files with a dot and thus “hide” them. It’s something we’re stuck with though.
A different use case is intermediate files. This isn’t consistent either of course, but looking to the node gitignore list linked earlier, there are many cases: `.nyc_output`, `.grunt`, `.rpt2_cache/`, `.rts2_cache_cjs/`, `.rts2_cache_es/`, `.rts2_cache_umd/`, `.cache`, `.parcel-cache`, `.next`, `.nuxt/`, `.cache/`, `.vuepress`, `.serverless`, `.fusebox`, `.dynamodb`, `.vscode-test`, `.yarn`.

Agreed they’re not special but I see correlation. And precedence, with ESLint.

> I wouldn’t like it, because IMO this means every repository that has issue templates needs an ignore file to unignore dotfiles. However, changing default behaviour would be a breaking change (semver major), whereas adding the ability to unignore files is a feature (semver minor).

Indeed.

I’m not 100% that `.github/` *should* be checked/formatted by default: issue/PR templates render differently from other markdown files: using a `h1` there comes out way too big and line wrapping will persist (`<br>`s). The form versions of templates seem like a much better idea.

 I’m quite happy that `.github/` isn’t checked by default for the places that unified has them. I’d probably ignore them if they would be checked by default.

**Comment by wooorm** [comment]
I don’t see a good enough reason to change the default. It seems to be something where some people prefer one or the other.
Both options will mean ignoring things. Whether ignoring intermediate dotfile folders (`.nyc_output, .grunt, .rpt2_cache/, .rts2_cache_cjs/, .rts2_cache_es/, .rts2_cache_umd/, .cache, .parcel-cache, .next, .nuxt/, .cache/, .vuepress, .serverless, .fusebox, .dynamodb, .vscode-test, .yarn`) or unignoring some dotfile folders (`.github, .gitlab`). Adding more patterns to the default (like `node_modules`) is also a slippery slope (e.g., some people do want `node_modules` checked).
In many cases, you can pass `.github` or whatever files you want in directly to the engine. For other cases, I’m open to adding support for negated dotfiles (`!.*`).

**Comment by djmcgreal-cc** [comment]
Can we unignore files starting with a `.` already? Sorry it wasn't clear to me from the conversation so far.

**Comment by wooorm** [comment]
Yeah, pass them (or node_modules) as files or globs explicitly.

P.s. With time I'm leaning a little more towards favouring this. What's everybody else thinking?

**Comment by remcohaszing** [comment]
I’m still in favour of not ignoring dotfiles by default. Recently I’ve been using [Changesets](https://github.com/changesets/changesets) in some projects, which uses markdown files in a `.changeset` directory. I find it unfortunate those aren’t checked using remark. I still also think the `.github` and `.gitlab` directories should be checked. Dotfiles just aren’t special IMO. They can be ignored explicitly if desired just like any other file.

**Comment by djmcgreal-cc** [comment]
Thanks
