### ISSUE TITLE
Only the first vfile is processed

### ISSUE THREAD

**Issue by remcohaszing** [unifiedjs/unified-engine#57]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

unified-engine@9.0.4

### Steps to reproduce

Run the following script:

```js
#!/usr/bin/env node
import {unified} from 'unified'
import {engine} from 'unified-engine'
import {VFile} from 'vfile'

function plugin() {
  this.Parser = () => ({type: 'root'})
  this.Compiler = () => ''

  return (ast, file) => {
    file.message('Oh noez!')
  }
}

const files = [
  new VFile({path: new URL('file:///a.txt'), value: 'a'}),
  new VFile({path: new URL('file:///b.txt'), value: 'b'})
]

engine(
  {
    files,
    processor: unified().use(plugin)
  },
  (error, code, context) => {
    console.dir(context.files, {depth: 3})
  }
)
```

### Expected behavior

For all given files the unified plugins are ran.

### Actual behavior

Unified plugins are only run for the first vfile given.

If file paths are given as strings instead of vfiles, all given paths are processed.

If a combination of vfiles and string paths is given, all string paths are processed up to the first vfile.

### Runtime

Node v16

### Package manager

npm v6

### OS

Linux

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by wooorm** [comment]
Running with debugging on probably provides more insight.
My hunch would be somewhere here: https://github.com/unifiedjs/unified-engine/tree/main/lib/file-pipeline.

**Comment by wooorm** [comment]
released!
