### ISSUE TITLE
Trough functions should be async

### ISSUE THREAD

**Issue by rkesters** [unifiedjs/unified-engine#62]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Trough native supports middle-ware return promises, but all of the unified middle-ware are sync functions. This cause a problem when creating some plugins. 

### Solution

Update at least the stringify functions to be async and add a `await` call to the context.prcessor.stringify() .

### Alternatives

Could assert that all plug-ins are sync, but no need when trough handles async for us.

**Comment by wooorm** [comment]
what where huh? Which plugins. Which functions.

**Comment by rkesters** [comment]
@wooorm I submitted a pull request for this #63

**Comment by ChristianMurphy** [comment]
@rkesters could you expand a bit on what type of plugin you are working with? (is this related to https://github.com/rkesters/remark-pdf?)
And what the particular issue you are running into is?

In particular a sandbox with an example would be very helpful, there are a few starters which may help:

| description | codesandbox | stackblitz |
| - | - | - |
| remark only (for markdown to markdown) | [codesandbox](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/remark-with-parcel) | [stackblitz](https://stackblitz.com/github/remarkjs/.github/tree/main/sandbox-templates/remark-with-parcel) |
| remark and rehype (for markdown to html) | [codesandbox](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/remark-rehype-with-parcel) | [stackblitz](https://stackblitz.com/github/remarkjs/.github/tree/main/sandbox-templates/remark-rehype-with-parcel) |
| react-markdown | [codesandbox](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/react-markdown-with-create-react-app) | [stackblitz](https://stackblitz.com/github/remarkjs/.github/tree/main/sandbox-templates/react-markdown-with-create-react-app) |

**Comment by rkesters** [comment]
@ChristianMurphy I forked remark-pdf because it was not working. During my debugging of it I found that it called a pdfmake to generate the pdf. pdfmake has a function getBuffer that takes a callback, which @inokawa wrapped in a promise [(see line)](https://github.com/rkesters/remark-pdf/blob/82c47b54525a08185e0129be09b6c4a57f17e96a/src/plugin.ts#L21)

However this promise is not resolved before it is [used](https://github.com/unifiedjs/unified-engine/blob/19a498e9c42bf103b885b969e874c2790d4ead81/lib/file-pipeline/stringify.js#L59).  

hence if we make [file-pipeline/stringify](https://github.com/rkesters/unified-engine/blob/af3427e165a58888cde2247083996487c42d99d6/lib/file-pipeline/stringify.js#L19) an async function, and add an [await](https://github.com/rkesters/unified-engine/blob/af3427e165a58888cde2247083996487c42d99d6/lib/file-pipeline/stringify.js#L59) , then compiler plugins can be async. 

Since trough can handle middle-ware functions that return promises or non-promises, this change results in no side affect for those not using async plugins.

**Comment by wooorm** [comment]
unified’s functions `parse` and `stringify` are sync. They are not async. They do not accept promises. And they never will be. This is a design decision.

Here is the documentation for parse: https://github.com/unifiedjs/unified#processorparsefile.
And here for stringify: https://github.com/unifiedjs/unified#processorstringifynode-file.

pdfmake does seem to have sync functionality.
There are also many ways to create PDFs, so perhaps you can find one that does not require a promise in `.stringify`

**Comment by rkesters** [comment]
> unified’s functions `parse` and `stringify` are sync. They are not async. They do not accept promises. And they never will be. This is a design decision.
> 
> Here is the documentation for parse: https://github.com/unifiedjs/unified#processorparsefile. And here for stringify: https://github.com/unifiedjs/unified#processorstringifynode-file.
> 
> pdfmake does seem to have sync functionality. There are also many ways to create PDFs, so perhaps you can find one that does not require a promise in `.stringify`

@wooorm 
But why is this a design decision? There does not appear to an architectural reason for it; given that trough hides the async nature of the functions. So is this just personal preference?
