### ISSUE TITLE
Incorrect reference to `injectPlugins` in plugins.md

### ISSUE THREAD

**Issue by siefkenj** [unifiedjs/unified-engine#66]
The `plugins.md` documentation refers to `injectPlugins`, however, this doesn't seem to be an option for unified-engine. Looking at the source code, it appears that a plugin function can be passed directly in the `plugins` array.

**Comment by wooorm** [comment]
Which doc refers to `injectPlugins`? 🤔

**Comment by siefkenj** [comment]
https://github.com/unifiedjs/unified-engine/blob/main/doc/plugins.md

It is actually `injectedPlugins`.

**Comment by wooorm** [comment]
Oh that should be `plugins` I think?

**Comment by wooorm** [comment]
Solved, thanks!
