### ISSUE TITLE
upgrade `load-plugin` (breaking change?)

### ISSUE THREAD

**Issue by JounQin** [unifiedjs/unified-engine#67]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

unified-engine

### Steps to reproduce

https://github.com/wooorm/load-plugin/issues/13

### Expected behavior

Install without desperation warning

### Actual behavior

warning

**Comment by carlosjeurissen** [comment]
This causes https://github.com/stylelint/stylelint and other plugins to raise the following warning:
```
 WARN  deprecated libnpmconfig@1.2.1: This module is not used anymore. npm config is parsed by npm itself and by @npmcli/config
```

Upon installation.
